{
  pkgs,
  lib,
  config,
  ...
}:

with lib;
let
  cfg = config.modules.niri;
  term = config.modules.terminal-emulator;
  wallpaper = ../../../wallpaper.png;
in
{
  options.modules.niri = {
    enable = mkEnableOption "niri";
  };

  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      wl-clipboard # `wl-copy` and `wl-paste`
      nemo
      imv # image viewer
      bibata-cursors # cursor theme (X11 format; niri uses it via the cursor section + XCURSOR_* env)
      xwayland-satellite # niri auto-starts this for X11 apps (it must be in $PATH)
      slurp # region selection for screenshots
      grim # screenshots
      swaybg # wallpapers (spawn-at-startup in the config below)
    ];

    home.pointerCursor = {
      enable = true;
      name = "Bibata-Modern-Classic";
      package = pkgs.bibata-cursors;
      size = 24;
      gtk.enable = true;
    };

    services.gammastep = {
      enable = true;
      provider = "manual";
      latitude = 52.3728;
      longitude = 4.8936;
    };

    programs.rofi = {
      enable = true;
      plugins = with pkgs; [ rofi ];
      extraConfig = {
        show-icons = true;
        terminal = term.binary;
      };
    };

    # Generate ~/.config/niri/config.kdl. This is a straight port of the old
    # Hyprland config (wallpaper, theme colors, shortcuts, workspace layout),
    # adapted to niri's KDL format and scrollable-tiling model.
    xdg.configFile."niri/config.kdl".text = ''
      // Generated by nix (modules/home-manager/niri/default.nix)
      // from the previous Hyprland configuration.

      output "DP-2" {
          // Must match the exact DRM mode name; "2560x1440@144" does not
          // match "2560x1440@144.006", so niri falls back to 60 Hz.
          mode "2560x1440@144.006"
          // position x=0 y=0 (single output; niri places it automatically)
      }

      spawn-at-startup "swaybg" "--image" "${wallpaper}"

      environment {
          XCURSOR_THEME "Bibata-Modern-Classic"
          XCURSOR_SIZE "24"
      }

      cursor {
          // bibata-cursors ships only the X11 format, so use it via xcursor.
          xcursor-theme "Bibata-Modern-Classic"
          xcursor-size 24
      }

      input {
          keyboard {
              xkb {
                  model "pc105"
                  layout "us"
                  // variant "intl"
              }
              repeat-rate 100
              repeat-delay 200
          }
          // touchpad natural-scroll is off by default (matches the old setting)
          mouse {
              accel-profile "flat"
              accel-speed 0
          }
          focus-follows-mouse
      }

      layout {
          // Hyprland had gaps_in 10 / gaps_out 40; niri's `gaps` is the inner
          // gap and `struts` act as fixed outer gaps.
          gaps 10
          struts {
              left 40
              right 40
              top 40
              bottom 40
          }
          default-column-width { proportion 0.5; }
          // Hyprland 1px borders (col.active_border / col.inactive_border)
          // become niri's focus ring; the active gradient is approximated
          // with its brightest color. Values are derived from the stylix
          // base16 scheme (Nord): active = base0D (#81a1c1), inactive = base01,
          // shadow = base00 (nord0) at ~53% alpha.
          focus-ring {
              width 1
              active-color "#${config.lib.stylix.colors.base0D}"
              inactive-color "#${config.lib.stylix.colors.base01}"
          }
          // Hyprland shadow was enabled; niri shadows are much simpler.
          shadow {
              on
              softness 30
              spread 0
              offset x=0 y=5
              color "#${config.lib.stylix.colors.base00}88"
          }
      }

      // Ask clients to omit server-side decorations so niri can draw
      // the focus ring / rounded corners correctly.
      prefer-no-csd

      hotkey-overlay {
          skip-at-startup
      }

      screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

      // Hyprland: decoration.rounding = 20, blur on for every window.
      window-rule {
          geometry-corner-radius 20
          clip-to-geometry true
          background-effect {
              blur true
          }
      }

      // Static workspaces w1..w9 (mirrors the old 9 Hyprland workspaces,
      // all pinned to DP-2). Bound as w1..w8 on the same keys as before.
      workspace "w1" { open-on-output "DP-2"; }
      workspace "w2" { open-on-output "DP-2"; }
      workspace "w3" { open-on-output "DP-2"; }
      workspace "w4" { open-on-output "DP-2"; }
      workspace "w5" { open-on-output "DP-2"; }
      workspace "w6" { open-on-output "DP-2"; }
      workspace "w7" { open-on-output "DP-2"; }
      workspace "w8" { open-on-output "DP-2"; }
      workspace "w9" { open-on-output "DP-2"; }

      binds {
          // ── launchers / window control (ported from Hyprland) ──
          Mod+Return hotkey-overlay-title="Open a Terminal" { spawn "${term.name-in-shell}"; }
          Mod+Q { close-window; }
          Mod+Space hotkey-overlay-title="Run an Application" { spawn "rofi" "-show" "drun"; }
          Mod+X { spawn "rofi" "-modi" "emoji" "-show" "emoji"; }
          // Mod+R was `hyprctl reload`; niri hot-reloads config on change,
          // so this is free for cycling column widths.
          Mod+R { switch-preset-column-width; }
          Mod+F { toggle-windowed-fullscreen; } // was `fullscreen`
          Mod+V { toggle-window-floating; }
          Mod+W hotkey-overlay-title="Open Firefox" { spawn "firefox"; }
          Mod+A { spawn "${term.new-window-with-commad}" "${pkgs.pulsemixer}/bin/pulsemixer"; }
          Mod+S hotkey-overlay-title="Screenshot a region" { spawn-sh "slurp | xargs -I{} ${pkgs.grim}/bin/grim -g {}"; }

          // ── focus cycling (was cyclenext / cyclenext, prev) ──
          Mod+N { focus-column-left-or-last; }
          Mod+M { focus-column-right-or-first; }

          // ── swap with neighbour (was swapnext / swapnext, prev) ──
          Mod+Ctrl+N { swap-window-right; }
          Mod+Ctrl+M { swap-window-left; }

          // ── workspaces (same keys: j k l ; u i o p → 1..8) ──
          Mod+J { focus-workspace "w1"; }
          Mod+K { focus-workspace "w2"; }
          Mod+L { focus-workspace "w3"; }
          Mod+Semicolon { focus-workspace "w4"; }
          Mod+U { focus-workspace "w5"; }
          Mod+I { focus-workspace "w6"; }
          Mod+O { focus-workspace "w7"; }
          Mod+P { focus-workspace "w8"; }

          Mod+Ctrl+J { move-window-to-workspace "w1"; }
          Mod+Ctrl+K { move-window-to-workspace "w2"; }
          Mod+Ctrl+L { move-window-to-workspace "w3"; }
          Mod+Ctrl+Semicolon { move-window-to-workspace "w4"; }
          Mod+Ctrl+U { move-window-to-workspace "w5"; }
          Mod+Ctrl+I { move-window-to-workspace "w6"; }
          Mod+Ctrl+O { move-window-to-workspace "w7"; }
          Mod+Ctrl+P { move-window-to-workspace "w8"; }

          // ── volume (same as before) ──
          XF86AudioRaiseVolume allow-when-locked=true { spawn-sh "wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+"; }
          XF86AudioLowerVolume allow-when-locked=true { spawn-sh "wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-"; }

          // ── workspace switching with the wheel (was mouse_down/mouse_up) ──
          Mod+WheelScrollDown cooldown-ms=150 { focus-workspace-down; }
          Mod+WheelScrollUp cooldown-ms=150 { focus-workspace-up; }

          // ── niri-native extras (non-conflicting defaults) ──
          Mod+Shift+Slash { show-hotkey-overlay; }

          Mod+Left  { focus-column-left; }
          Mod+Down  { focus-window-down; }
          Mod+Up    { focus-window-up; }
          Mod+Right { focus-column-right; }

          Mod+Ctrl+Left  { move-column-left; }
          Mod+Ctrl+Down  { move-window-down; }
          Mod+Ctrl+Up    { move-window-up; }
          Mod+Ctrl+Right { move-column-right; }

          Mod+Home { focus-column-first; }
          Mod+End  { focus-column-last; }
          Mod+Ctrl+Home { move-column-to-first; }
          Mod+Ctrl+End  { move-column-to-last; }

          Mod+BracketLeft  { consume-or-expel-window-left; }
          Mod+BracketRight { consume-or-expel-window-right; }
          Mod+Comma  { consume-window-into-column; }
          Mod+Period { expel-window-from-column; }

          Mod+C { center-column; }
          Mod+Ctrl+C { center-visible-columns; }
          Mod+Ctrl+F { expand-column-to-available-width; }

          Mod+Minus { set-column-width "-10%"; }
          Mod+Equal { set-column-width "+10%"; }
          Mod+Shift+Minus { set-window-height "-10%"; }
          Mod+Shift+Equal { set-window-height "+10%"; }

          Mod+Shift+V { switch-focus-between-floating-and-tiling; }
          Mod+Shift+W { toggle-column-tabbed-display; }
          Mod+Shift+F { fullscreen-window; }
          Mod+Shift+O { toggle-overview; }
          Mod+Shift+P { power-off-monitors; }

          Print { screenshot; }
          Ctrl+Print { screenshot-screen; }
          Alt+Print { screenshot-window; }

          Mod+Escape allow-inhibiting=false { toggle-keyboard-shortcuts-inhibit; }
          Mod+Shift+E { quit; }
          Ctrl+Alt+Delete { quit; }
      }
    '';
  };
}
