staging-mysql-url = "mysql://acme:hunter2@database.com:3306"
jira-url = "https://acmeinc.atlassian.net/browse/"
domain = "acme.com"
demo-db-user = "acme"
demo-db-password = "hunter2"
natstaging-user = "acme"

[ips]
staging = "6.969.696.969"
natstaging-range = "6.969.696.*"
staging = "6.969.696.969"
staging-graylog = "6.969.696.969"
demo-px = "6.969.696.969"

[extra-bookmarks]
"oncall chart" = "https://docs.google.com/spreadsheets/"
